# relay type, either 'skopeo' or 'docker'
relay: docker

# relay config sections
skopeo:
  # path to the skopeo binary; defaults to 'skopeo', in which case it needs to
  # be in PATH
  binary: skopeo
  # directory under which to look for client certs & keys, as well as CA certs
  # (see note below)
  certs-dir: /etc/skopeo/certs.d

docker:
  # Docker host to use as the relay
  dockerhost: unix:///var/run/docker.sock
  # Docker API version to use, defaults to 1.24
  api-version: 1.24

# list of sync tasks
tasks:

  - name: task1 # required

    # interval in seconds at which the task should be run; when omitted,
    # the task is only run once at start-up
    #interval: 60

    # determines whether for this task, more verbose output should be
    # produced; defaults to false when omitted
    #verbose: true

    # 'source' and 'target' are both required and describe the source and
    # target registries for this task:
    #  - 'registry' points to the server; required
    #  - 'auth' contains the base64 encoded credentials for the registry
    #    in JSON form {"username": "...", "password": "..."}
    #  - 'auth-refresh' specifies an interval for automatic retrieval of
    #    credentials; only for AWS ECR (see below)
    #  - 'skip-tls-verify' determines whether to skip TLS verification for the
    #    registry server (only for 'skopeo', see note below); defaults to false
    source:
      registry: registry.hub.docker.com
      #auth: eyJ1c2VybmFtZSI6ICJhbGV4IiwgInBhc3N3b3JkIjogInNlY3JldCJ9Cg==
    target:
      registry: 172.18.18.1:6666
      auth: eyJ1c2VybmFtZSI6ICJhbGV4IiwgInBhc3N3b3JkIjogImFsc29zZWNyZXQifQo=
      #skip-tls-verify: true

    # 'mappings' is a list of 'from':'to' pairs that define mappings of image
    # paths in the source registry to paths in the destination; 'from' is
    # required, while 'to' can be dropped if the path should remain the same as
    # 'from'. Additionally, the tags being synced for a mapping can be limited
    # by providing a 'tags' list. When omitted, all image tags are synced.
    mappings:
      # controller & compute
      - from: kolla/centos-binary-cron
        tags: ['queens']
      - from: kolla/centos-binary-fluentd
        tags: ['queens']
      - from: kolla/centos-binary-kolla-toolbox
        tags: ['queens']
      # controller
      - from: kolla/centos-binary-barbican-api
        tags: ['queens']
      - from: kolla/centos-binary-barbican-keystone-listener
        tags: ['queens']
      - from: kolla/centos-binary-barbican-worker
        tags: ['queens']
      - from: kolla/centos-binary-glance-api
        tags: ['queens']
      - from: kolla/centos-binary-glance-registry
        tags: ['queens']
      - from: kolla/centos-binary-heat-api
        tags: ['queens']
      - from: kolla/centos-binary-heat-api-cfn
        tags: ['queens']
      - from: kolla/centos-binary-heat-engine
        tags: ['queens']
      - from: kolla/centos-binary-horizon
        tags: ['queens']
      - from: kolla/centos-binary-keystone
        tags: ['queens']
      - from: kolla/centos-binary-mariadb
        tags: ['queens']
      - from: kolla/centos-binary-memcached
        tags: ['queens']
      - from: kolla/centos-binary-neutron-server
        tags: ['queens']
      - from: kolla/centos-binary-nova-api
        tags: ['queens']
      - from: kolla/centos-binary-nova-conductor
        tags: ['queens']
      - from: kolla/centos-binary-nova-consoleauth
        tags: ['queens']
      - from: kolla/centos-binary-nova-novncproxy
        tags: ['queens']
      - from: kolla/centos-binary-nova-placement-api
        tags: ['queens']
      - from: kolla/centos-binary-nova-scheduler
        tags: ['queens']
      - from: kolla/centos-binary-rabbitmq
        tags: ['queens']
      - from: kolla/centos-binary-swift-account
        tags: ['queens']
      - from: kolla/centos-binary-swift-base
        tags: ['queens']
      - from: kolla/centos-binary-swift-container
        tags: ['queens']
      - from: kolla/centos-binary-swift-object
        tags: ['queens']
      - from: kolla/centos-binary-swift-object-expirer
        tags: ['queens']
      - from: kolla/centos-binary-swift-proxy-server
        tags: ['queens']
      - from: kolla/centos-binary-swift-rsyncd
        tags: ['queens']
      # compute
      - from: kolla/centos-binary-nova-compute
        tags: ['queens']
      - from: kolla/centos-binary-nova-libvirt
        tags: ['queens']
      - from: kolla/centos-binary-nova-ssh
        tags: ['queens']

      # ovs
      - from: kolla/centos-binary-openvswitch-db-server 
        tags: ['queens']
      - from: kolla/centos-binary-openvswitch-vswitchd
        tags: ['queens']
      - from: kolla/centos-binary-neutron-openvswitch-agent
        tags: ['queens']
      - from: kolla/centos-binary-neutron-dhcp-agent
        tags: ['queens']
      - from: kolla/centos-binary-neutron-l3-agent
        tags: ['queens']
      - from: kolla/centos-binary-neutron-metadata-agent
        tags: ['queens']
