#!/bin/sh
#set -x
BUILDPLACE=/var/cache/pbuilder/cow.build

mkdir -p $BUILDPLACE

echo '*** login cow-shell ... ***'
cowbuilder --login \
    --buildplace $BUILDPLACE \
    --buildresult /usr/src/backports/$STABLE/ \
    --bindmounts /usr/src/backports/$STABLE/ \
    --hookdir /usr/src/backports/$STABLE/ "$@"
